const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const esbuild = require('esbuild');
const React = require('../operator-web/node_modules/react');
const { renderToStaticMarkup } = require('../operator-web/node_modules/react-dom/server');
const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'framer-components/public-probe/PublicNPSHoldings.tsx'), 'utf8');
const start = source.indexOf('// 되돌리지 말 것: 접수일');
const end = source.indexOf('export default function PublicNPSHoldings', start);
assert.ok(start >= 0 && end > start);
const code = esbuild.transformSync("const React=require('react');const {useState,useMemo}=React;" + source.slice(start, end) + '\nmodule.exports={NpsHistoryPanel,npsNumber};', {loader:'tsx',format:'cjs'}).code;
const mod = {exports:{}};
new Function('require','module','exports',code)(name => name === 'react' ? React : require(name), mod, mod.exports);
const { NpsHistoryPanel, npsNumber } = mod.exports;
const event = (pct, receipt='20260701000345') => ({pct, filed_at:'2026-07-01', rcept_no:receipt, qty:1000, qty_change:-100, pct_change_pp:-0.5, as_of:null});
const stock = (events, extra={}) => ({ticker:'005930',name:'검증용 기업',rank:1,selection_as_of:'2025-12-31',selection_pct:7.2,eval_amt_100m:100,status:'ok',events,...extra});
const render = (s, isDark=false) => renderToStaticMarkup(React.createElement(NpsHistoryPanel, {isDark,history:{selection:{as_of:'2025-12-31',limit:100},stocks:s ? [s] : []}}));
test('unknown is not a fabricated zero', () => { for(const v of [null,undefined,'',true,'NaN']) assert.equal(npsNumber(v),null); assert.equal(npsNumber(0),0); });
test('filing observations and signed quantity changes are explicit', () => { const html=render(stock([event(7.2)])); assert.match(html,/접수일은 매매일이 아니에요/);assert.match(html,/보유 수량 100주 감소/);assert.match(html,/지분 -0.50%p/);assert.match(html,/7.20%/);assert.match(html,/1\/100종목/); });
test('correction linkage blocks extrema and the interpolated line', () => { const html=render(stock([event(12),event(5,'20260701000346')],{observed_pct:{correction_links_unverified:true}})); assert.match(html,/정정 연결 확인 전/);assert.doesNotMatch(html,/<polyline/);const metrics=html.slice(html.indexOf('class="nh-metrics"'),html.indexOf('class="nh-summary"'));assert.doesNotMatch(metrics,/12.00%/); });
test('no report cannot imply no position or liquidation', () => { const html=render(stock([])); assert.match(html,/공시 없음은 미보유·전량 매도를 뜻하지 않아요/);assert.doesNotMatch(html,/<polyline/); });
test('missing payload retains basic information guidance', () => { assert.match(render(null),/아래 기본 보유 정보는 계속 볼 수 있어요/); });
test('source links cannot accept arbitrary URLs or malformed receipt IDs', () => { const html=render(stock([event(7.2,'javascript:alert(1)')]));assert.doesNotMatch(html,/href="javascript:/);assert.doesNotMatch(html,/공시 원문 ↗/); });
test('dark theme and compact accessible controls use the approved tokens', () => { const html=render(stock([event(7.2)]),true); assert.match(html,/#1d242c/);assert.match(html,/#e3e7ec/);assert.match(html,/height:44px/);assert.match(html,/aria-label="국민연금 상세 종목 검색"/);assert.match(html,/prefers-reduced-motion/); });
